(()=>{'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');let W=1280;const H=720,LEVEL_W=5200,GROUND=625,GRAVITY=1850;
const assets={hero:img('assets/hero-sprites.png'),monsters:img('assets/monster-sprites.png'),far:img('assets/map-far.png'),mid:img('assets/map-mid.png'),front:img('assets/map-front.png')};
const keys={left:false,right:false,jump:false,shoot:false,dash:false,capture:false};let running=false,last=0,camera=0,toastTimer=0,boss=null,won=false;
function resizeViewport(){const viewport=window.visualViewport||window;const vw=viewport.width||innerWidth,vh=viewport.height||innerHeight;W=Math.max(320,Math.min(1280,Math.round(H*vw/vh)));canvas.width=W;canvas.height=H;camera=Math.max(0,Math.min(LEVEL_W-W,camera));if(!running){drawBg();drawWorld();drawForeground()}}
addEventListener('resize',resizeViewport,{passive:true});if(window.visualViewport)visualViewport.addEventListener('resize',resizeViewport,{passive:true});
const saved=JSON.parse(localStorage.getItem('monster_buster_collection_v1')||'[]');
const player={x:120,y:GROUND-92,w:54,h:82,vx:0,vy:0,hp:100,maxHp:100,facing:1,onGround:false,coyote:0,jumpLock:false,dash:0,dashCd:0,shootCd:0,charge:0,hurt:0,anim:0};
const platforms=[{x:0,y:GROUND,w:900,h:95},{x:1030,y:GROUND,w:770,h:95},{x:1940,y:GROUND,w:980,h:95},{x:3050,y:GROUND,w:780,h:95},{x:3970,y:GROUND,w:1230,h:95},{x:520,y:490,w:220,h:24},{x:850,y:430,w:210,h:24},{x:1330,y:500,w:260,h:24},{x:1710,y:390,w:220,h:24},{x:2180,y:485,w:260,h:24},{x:2580,y:390,w:190,h:24},{x:3300,y:470,w:250,h:24},{x:3680,y:370,w:220,h:24},{x:4200,y:480,w:240,h:24}];
const types=[{name:'焰尾狐',col:0,color:'#ff7a32'},{name:'苔甲蟲',col:1,color:'#7fb53e'},{name:'雷翼蝠',col:2,color:'#b375ff'},{name:'泡泡怪',col:3,color:'#39dfff'}];
let enemies=[],shots=[],enemyShots=[],particles=[];
function img(src){const i=new Image();i.src=src;return i}
function reset(){Object.assign(player,{x:120,y:GROUND-92,vx:0,vy:0,hp:100,facing:1,onGround:false,dash:0,dashCd:0,shootCd:0,charge:0,hurt:0});camera=0;won=false;boss=null;shots=[];enemyShots=[];particles=[];enemies=[spawn(0,650),spawn(1,1180),spawn(2,1550),spawn(3,2060),spawn(0,2440),spawn(1,2780),spawn(2,3370),spawn(3,3710),spawn(0,4220)];updateHud()}
function spawn(type,x){return{x,y:GROUND-58,w:70,h:58,vx:0,hp:65,maxHp:65,type,dir:-1,t:Math.random()*4,hurt:0,dead:false}}
function rects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function toast(text,color='#e5fbff'){const el=document.querySelector('#toast');el.textContent=text;el.style.color=color;el.classList.add('show');toastTimer=1.5}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*330,vy:(Math.random()-.7)*260,life:.45+Math.random()*.4,color,r:2+Math.random()*4})}
function updateHud(){document.querySelector('#hp-bar').style.width=Math.max(0,player.hp)+'%';document.querySelector('#charge-bar').style.width=Math.min(100,player.charge/1.1*100)+'%';document.querySelector('#pet-count').textContent='圖鑑 '+new Set(saved.map(p=>p.type)).size+'/4';if(boss)document.querySelector('#boss-bar').style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%'}
function land(body,prevY){body.onGround=false;for(const p of platforms){if(body.x+body.w>p.x&&body.x<p.x+p.w&&prevY+body.h<=p.y+8&&body.y+body.h>=p.y&&body.vy>=0){body.y=p.y-body.h;body.vy=0;body.onGround=true}}}
function shoot(){if(player.shootCd>0)return;const power=Math.min(1,player.charge/1.1),charged=power>.7;player.shootCd=charged?.34:.16;shots.push({x:player.x+(player.facing>0?player.w:-16),y:player.y+31,w:charged?34:18,h:charged?18:10,vx:player.facing*(charged?820:680),dmg:charged?38:14,life:1.6,color:charged?'#b9fbff':'#42ddff'});burst(player.x+player.w/2,player.y+34,'#4de8ff',charged?10:4);player.charge=0}
function capture(){let target=null,d=Infinity;for(const e of enemies){if(e.dead)continue;const dist=Math.abs((e.x+e.w/2)-(player.x+player.w/2));if(dist<d){d=dist;target=e}}if(!target||d>260){toast('附近沒有可捕捉的魔獸');return}const ratio=target.hp/target.maxHp;if(ratio>.35){toast('先將 '+types[target.type].name+' 削弱至 35% 以下','#fde68a');return}const chance=.48+(1-ratio)*.55;burst(target.x+35,target.y+25,'#f8d34d',24);if(Math.random()>chance){toast('捕捉失敗！','#fb7185');target.vx=player.x<target.x?250:-250;return}target.dead=true;const pet={type:target.type,name:types[target.type].name,caughtAt:Date.now()};saved.push(pet);localStorage.setItem('monster_buster_collection_v1',JSON.stringify(saved));toast('捕捉成功：'+pet.name,'#86efac');updateHud()}
function hurt(amount,from){if(player.hurt>0)return;player.hp-=amount;player.hurt=.75;player.vx=player.x<from?-340:340;player.vy=-360;burst(player.x+27,player.y+35,'#ff6b6b',16);updateHud();if(player.hp<=0)finish(false)}
function input(dt){const accel=player.onGround?2300:1400;if(player.dash>0){player.dash-=dt;player.vx=player.facing*720}else{if(keys.left){player.vx-=accel*dt;player.facing=-1}if(keys.right){player.vx+=accel*dt;player.facing=1}if(!keys.left&&!keys.right)player.vx*=Math.pow(.002,dt);player.vx=Math.max(-330,Math.min(330,player.vx))}if(keys.jump&&!player.jumpLock&&(player.onGround||player.coyote>0)){player.vy=-690;player.onGround=false;player.coyote=0;player.jumpLock=true}if(!keys.jump)player.jumpLock=false;if(keys.dash&&player.dashCd<=0){player.dash=.18;player.dashCd=.75;burst(player.x,player.y+50,'#43e8ff',14)}if(keys.shoot)player.charge=Math.min(1.1,player.charge+dt);if(!keys.shoot&&player.charge>0)shoot();keys.dash=false;if(keys.capture){capture();keys.capture=false}}
function updatePlayer(dt){input(dt);player.coyote=player.onGround?.11:Math.max(0,player.coyote-dt);player.dashCd=Math.max(0,player.dashCd-dt);player.shootCd=Math.max(0,player.shootCd-dt);player.hurt=Math.max(0,player.hurt-dt);const prevY=player.y;player.vy+=GRAVITY*dt;player.x+=player.vx*dt;player.y+=player.vy*dt;player.x=Math.max(0,Math.min(LEVEL_W-player.w,player.x));land(player,prevY);if(player.y>H+200)hurt(30,player.x);if(player.y>H+250){player.x=Math.max(30,camera+80);player.y=100}player.anim+=dt*(3+Math.abs(player.vx)/70);camera+=((player.x-W*.36)-camera)*Math.min(1,dt*4);camera=Math.max(0,Math.min(LEVEL_W-W,camera));if(player.x>4550&&!boss)spawnBoss()}
function spawnBoss(){boss={x:4860,y:GROUND-150,w:112,h:150,hp:520,maxHp:520,t:0,shoot:1.1,hurt:0};document.querySelector('#boss-hud').classList.remove('hidden');toast('警告：核心守衛啟動','#fda4af')}
function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;e.t+=dt;e.hurt=Math.max(0,e.hurt-dt);const dx=player.x-e.x;e.dir=dx<0?-1:1;if(Math.abs(dx)<520){e.vx+=e.dir*330*dt;if(Math.abs(dx)<190&&Math.random()<dt*.8)enemyShots.push({x:e.x+35,y:e.y+25,w:12,h:12,vx:e.dir*300,vy:-20,dmg:8,life:2,color:types[e.type].color})}else e.vx*=.96;e.vx=Math.max(-95,Math.min(95,e.vx));e.x+=e.vx*dt;if(rects(player,e))hurt(9,e.x)}enemies=enemies.filter(e=>!e.dead&&e.x>-100&&e.x<LEVEL_W+100)}
function updateBoss(dt){if(!boss)return;boss.t+=dt;boss.hurt=Math.max(0,boss.hurt-dt);boss.y=GROUND-boss.h+Math.sin(boss.t*2)*10;boss.shoot-=dt;if(boss.shoot<=0){boss.shoot=.7+Math.random()*.55;const a=Math.atan2(player.y+35-boss.y-65,player.x-boss.x);for(let n=-1;n<=1;n++)enemyShots.push({x:boss.x,y:boss.y+60,w:18,h:18,vx:Math.cos(a+n*.18)*390,vy:Math.sin(a+n*.18)*390,dmg:12,life:3,color:'#ff5577'})}if(rects(player,boss))hurt(14,boss.x);updateHud()}
function updateProjectiles(dt){for(const s of shots){s.x+=s.vx*dt;s.life-=dt;for(const e of enemies){if(!e.dead&&rects(s,e)){e.hp-=s.dmg;e.hurt=.15;s.life=0;burst(s.x,s.y,types[e.type].color,7);if(e.hp<=0){e.dead=true;burst(e.x+35,e.y+25,types[e.type].color,20)}}}if(boss&&rects(s,boss)){boss.hp-=s.dmg;boss.hurt=.12;s.life=0;burst(s.x,s.y,'#fb7185',9);if(boss.hp<=0){burst(boss.x+55,boss.y+70,'#67e8f9',50);boss=null;document.querySelector('#boss-hud').classList.add('hidden');finish(true)}}}shots=shots.filter(s=>s.life>0&&s.x>camera-50&&s.x<camera+W+100);for(const s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(rects(s,player)){hurt(s.dmg,s.x);s.life=0}}enemyShots=enemyShots.filter(s=>s.life>0)}
function petAssist(dt){if(!saved.length)return;const p=saved[saved.length-1];p.cool=(p.cool||0)-dt;if(p.cool<=0){const target=enemies.find(e=>!e.dead&&Math.abs(e.x-player.x)<500);if(target){p.cool=1.25;shots.push({x:player.x-10,y:player.y+10,w:12,h:12,vx:(target.x>player.x?1:-1)*520,dmg:8,life:1.4,color:types[p.type].color})}}}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);if(toastTimer>0&&(toastTimer-=dt)<=0)document.querySelector('#toast').classList.remove('show')}
function tiledLayer(image,offset,alpha=1,scale=1){const dw=W*1.7*scale,dh=H,x=-((offset%dw)+dw)%dw;ctx.globalAlpha=alpha;ctx.drawImage(image,0,0,image.width||2172,image.height||724,x,0,dw,dh);ctx.drawImage(image,0,0,image.width||2172,image.height||724,x+dw,0,dw,dh);ctx.globalAlpha=1}
function drawBg(){ctx.fillStyle='#09112c';ctx.fillRect(0,0,W,H);tiledLayer(assets.far,camera*.08,1,1);tiledLayer(assets.mid,camera*.28,.76,1);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#04102411');g.addColorStop(1,'#02050d88');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawForeground(){tiledLayer(assets.front,camera*.72,.74,1)}
function drawWorld(){ctx.save();ctx.translate(-camera,0);for(const p of platforms){ctx.fillStyle='#101e2d';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#1dd8e8';ctx.fillRect(p.x,p.y,p.w,5);ctx.fillStyle='#274154';for(let x=p.x+18;x<p.x+p.w;x+=45)ctx.fillRect(x,p.y+14,22,5)}for(const e of enemies)drawMonster(e);if(boss)drawBoss();for(const s of shots)drawShot(s);for(const s of enemyShots)drawShot(s);drawPlayer();drawPet();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/.7);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.restore()}
function drawPlayer(){const moving=Math.abs(player.vx)>40,air=!player.onGround;let frame=air?(player.vy<0?6:7):(moving?2+Math.floor(player.anim)%4:Math.floor(player.anim*.35)%2);if(player.dash>0)frame=10;else if(player.hurt>0)frame=11;else if(player.charge>.15)frame=moving?9:8;const sw=assets.hero.width/4||362,sh=assets.hero.height/3||362,sx=(frame%4)*sw,sy=Math.floor(frame/4)*sh;ctx.save();ctx.translate(player.x+player.w/2,player.y+player.h/2);ctx.scale(player.facing,1);if(player.hurt>0&&Math.floor(player.hurt*20)%2)ctx.globalAlpha=.35;ctx.drawImage(assets.hero,sx,sy,sw,sh,-62,-75,124,124);ctx.restore()}
function drawMonster(e){const sw=assets.monsters.width/4||362,sh=assets.monsters.height/3||362,row=e.hurt>0?2:(Math.floor(e.t*5)%2);ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);ctx.scale(e.dir<0?1:-1,1);ctx.drawImage(assets.monsters,e.type*sw,row*sh,sw,sh,-55,-55,110,110);ctx.restore();ctx.fillStyle='#07101d';ctx.fillRect(e.x,e.y-10,e.w,6);ctx.fillStyle=types[e.type].color;ctx.fillRect(e.x,e.y-10,e.w*Math.max(0,e.hp/e.maxHp),6)}
function drawBoss(){ctx.save();ctx.translate(boss.x+boss.w/2,boss.y+boss.h/2);if(boss.hurt>0)ctx.globalAlpha=.45;ctx.fillStyle='#0a1527';ctx.strokeStyle='#ff5478';ctx.lineWidth=6;ctx.beginPath();ctx.roundRect(-55,-72,110,144,28);ctx.fill();ctx.stroke();ctx.fillStyle='#5eeaff';ctx.fillRect(-28,-38,56,18);ctx.fillStyle='#fb7185';ctx.beginPath();ctx.arc(0,18,27,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawShot(s){ctx.save();ctx.shadowBlur=16;ctx.shadowColor=s.color;ctx.fillStyle=s.color;ctx.beginPath();ctx.ellipse(s.x+s.w/2,s.y+s.h/2,s.w/2,s.h/2,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawPet(){if(!saved.length)return;const p=saved[saved.length-1],t=performance.now()/500,x=player.x-45*player.facing+Math.sin(t)*6,y=player.y+8+Math.cos(t)*8,sw=assets.monsters.width/4||362,sh=assets.monsters.height/3||362;ctx.drawImage(assets.monsters,p.type*sw,0,sw,sh,x-28,y-28,56,56)}
function finish(success){if(!running)return;running=false;won=success;document.querySelector('#result-title').textContent=success?'任務完成':'任務失敗';document.querySelector('#result-copy').textContent=success?'核心守衛已解除。已捕捉魔獸會在下次任務中支援你。':'獵捕者失去戰鬥能力，重新調整編隊後再出發。';document.querySelector('#result').classList.remove('hidden')}
function loop(ts){if(!running)return;const dt=Math.min(.033,(ts-last)/1000||.016);last=ts;updatePlayer(dt);updateEnemies(dt);updateBoss(dt);updateProjectiles(dt);petAssist(dt);updateParticles(dt);drawBg();drawWorld();drawForeground();updateHud();requestAnimationFrame(loop)}
function setKey(k,on){if(k==='KeyA'||k==='ArrowLeft')keys.left=on;if(k==='KeyD'||k==='ArrowRight')keys.right=on;if(k==='Space'||k==='KeyW'||k==='ArrowUp')keys.jump=on;if(k==='KeyJ')keys.shoot=on;if(k==='KeyK'&&on)keys.dash=true;if(k==='KeyL'&&on)keys.capture=true}
addEventListener('keydown',e=>{setKey(e.code,true);if(['Space','ArrowLeft','ArrowRight','ArrowUp'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>setKey(e.code,false));
document.querySelectorAll('[data-key]').forEach(b=>{const name=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[name]=true;b.setPointerCapture(e.pointerId)});const off=e=>{e.preventDefault();if(name==='shoot'&&keys.shoot)shoot();keys[name]=false};b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)});
document.querySelector('#start-btn').onclick=()=>{document.querySelector('#start').classList.add('hidden');reset();running=true;last=performance.now();requestAnimationFrame(loop)};document.querySelector('#restart-btn').onclick=()=>{document.querySelector('#result').classList.add('hidden');reset();running=true;last=performance.now();requestAnimationFrame(loop)};
resizeViewport();reset();drawBg();drawWorld();drawForeground();
})();
